### ISSUE TITLE
如何从onenote一键推送到自己的hexo博客?

### ISSUE THREAD

**Issue by zbuhui-win** [juforg/hexo-deployer-metaweblog#1]
将自己的hexo博客部署到github,cnblogs提供了MetaWeblogAPI .我希望能在onenote上一键发布到cnblogs和hexo博客,前者已经实现,后者不知道用什么方法,方便讲下么 ?谢谢

**Comment by juforg** [comment]
hexo是静态博客，后台是纯html，想从onenote发布，一个思路就是onenote开发个插件将静态的html文件通过git提交，不过意义应该不大，不经过hexo客户端的编译，想要在hexo中正常显示，需要做的事情太多，这个思路基本行不通，另一思路就是开发插件将onenote的markdown文件复制到本地hexo的目录，再调用命令hexo g & hexo g

**Comment by cpu100** [comment]
感觉 XML-PRC 这个协议有点不雅观啊，还占了这么个通用的名字

**Comment by cpu100** [comment]
好厌恶XML
